# Generated by Django 4.1.1 on 2022-09-27 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="authors",
            field=models.ManyToManyField(related_name="authors", to="mainapp.author"),
        ),
    ]
