# Generated by Django 4.1.1 on 2022-09-30 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0002_alter_book_authors"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={"ordering": ["?"]},
        ),
    ]
