# Generated by Django 4.1.1 on 2022-09-25 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bookuser",
            name="gender",
        ),
    ]
