# Generated by Django 4.1.1 on 2022-09-25 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authapp", "0002_remove_bookuser_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookuser",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="users_avatars/default.png",
                upload_to="users_avatars",
            ),
        ),
    ]
