# Generated by Django 4.1.1 on 2022-09-26 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authapp", "0003_alter_bookuser_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookuser",
            name="age",
            field=models.PositiveIntegerField(default=18),
        ),
    ]
