# Generated by Django 4.1.1 on 2022-09-29 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authapp", "0004_alter_bookuser_age"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookuser",
            name="city",
            field=models.CharField(default="Los Angeles", max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bookuser",
            name="country",
            field=models.CharField(default="USA", max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bookuser",
            name="postcode",
            field=models.PositiveIntegerField(default=35009),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bookuser",
            name="street",
            field=models.CharField(default="Gagarin Street", max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bookuser",
            name="street_number",
            field=models.PositiveIntegerField(default=65),
            preserve_default=False,
        ),
    ]
