# Generated by Django 4.1.1 on 2022-09-29 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cartapp", "0002_alter_cart_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cart",
            options={"ordering": ["-book"]},
        ),
    ]
